### PR TITLE
Add GPL-3 license and tidy-github docs

### PR DESCRIPTION
**Pull request by batpigandme**
For JOSS paper. cc @hadley

### CODE REVIEW

**Comment by jimhester** [comment]
Hmm, not sure if we can change this to GPL-3, `GPL-2 (>=2)` is kind of vague, but seems more GPL-2 then three to me, changing it means we probably have to get approval from all the contributors.

**Comment by hadley** [comment]
Oh yeah, we shouldn't change; @batpigandme just do what we did to the other packages in this situation

**Comment by batpigandme** [comment]
Sorry, dropped the ball on this! Changed it back to GPL 2, @hadley!

**Comment by jimhester** [comment]
Thanks!

**Pull request merged**
