### PR TITLE
export classes and add docs

### PR DESCRIPTION
**Pull request by nuest**
see #248

`setOldClass` seems to require some manual definitions in roxygen, I followed https://stackoverflow.com/questions/7758748/documenting-setas-and-setoldclass-with-roxygen#7766762

### CODE REVIEW

**Comment by jimhester** [comment]
Thanks! I ended up doing this in a somewhat simpler fashion. I will release an updated version of xml2 next week with this fix included, and you can submit sos4R at that time.

**Comment by jimhester** [comment]
Oh, now I see you get a note if the classes are undocumented, so I will actually just use this PR afterall :)

**Comment by nuest** [comment]
:smiley: 

I did the same thing: "Oh, that was quick to fix" and then `R CMD check` comes along and gives you a slap on the wrist. :man_shrugging:

**Comment by nuest** [comment]
@jimhester Do you plan a bugfix release for this? Otherwise I'll ask CRAN to admit sos4R despite the warning..

**Comment by jimhester** [comment]
Yes, I will send a release early next week.

**Pull request merged**
